version: '3.9'

services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: MONGO_INITDB_ROOT_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
        ports:
            - 27017:27017
